ci: Retry entire osx-build-dmg task up to 10 times
Commit 1b2dd29e8298270a96659082f3afffd06e9f9517 made the `hdiutil
create` command be retried up to 10 times to fix it occasionally failing
on the CI, but missed other hdiutil calls that also frequently fail.

This commit reverts 1b2dd29e8298270a96659082f3afffd06e9f9517 and instead
retries the entire osx-build-dmg step in the CI up to 10 times. This
also has the advantage of keeping this workaround contained in ci.yml.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -173,7 +173,18 @@ jobs:
         if: startsWith(matrix.config.os, 'macos-')
         run: |
           meson compile osx-bundle -C build
-          meson compile osx-build-dmg -C build
+
+          # Run osx-build-dmg but retry up to 10 times if it fails since hdiutil can be unreliable
+          # See: https://github.com/actions/runner-images/issues/7522
+          max_tries=10
+          i=0
+          until meson compile osx-build-dmg -C build ; do
+            if [ $i -eq $max_tries ]; then
+              echo "Error: osx-build-dmg failed after ${max_tries} tries."
+              exit 1
+            fi
+            i=$((i+1))
+          done
 
       - name: Upload artifacts - macOS dmg
         uses: actions/upload-artifact@v6
